version: "3.7"
services:
  app:
    stdin_open: true
    tty: true
    build:
      context: .
      args:
        - USER=${CONTAINER_USER:-root}
        - USER_ID=${CONTAINER_USER_ID:-0}
        - GROUP=${CONTAINER_GROUP:-root}
        - GROUP_ID=${CONTAINER_GROUP_ID:-0}
    env_file: .env
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
      - log_data:/tmp
    command: sh -c "bundle && bundle exec ruby app.rb -o 0.0.0.0 -p 3333"
    ports:
      - "${SINATRA_PORT:-3333}:3333"
volumes:
  bundle_data:
  log_data:
    external:
      name: "${EXTERNEL_LOG_VOLUME:-stump_bundle_data}" # FIXME: 未指定の場合、マウントするのヤメたいけど。。。
networks:
  default:
    external:
      name: "${NETWORK:-bridge}"
