database:
  development:
    adapter: mysql2
    database: DATABASE_NAME
    host: LOCALHOST
    username: USERNAME
    password: PASSWORD
    port: 3306

ignore_tables:
  - audits
  - ar_internal_metadata
  - schema_migrations

stamp_path: stamps
